#include "codegen.hpp"
#include <sstream>
#include <stdexcept>

CodeGenerator::CodeGenerator() 
    : m_labelCounter(0), m_currentOffset(0) {
    // 初始化寄存器分配表（R0-R7）
    m_registers.resize(8, false);
}

std::string CodeGenerator::generate(Program& program) {
    m_output.clear();
    m_labelCounter = 0;
    m_currentOffset = 0;
    
    // 访问程序节点
    program.accept(*this);
    
    return m_output;
}

void CodeGenerator::emit(const std::string& code) {
    m_output += code + "\n";
}

void CodeGenerator::emitLabel(const std::string& label) {
    m_output += label + ":\n";
}

std::string CodeGenerator::newLabel() {
    return "L" + std::to_string(m_labelCounter++);
}

void CodeGenerator::pushScope() {
    // 作用域管理（简化实现）
}

void CodeGenerator::popScope() {
    // 作用域管理（简化实现）
}

int CodeGenerator::allocateRegister() {
    for (int i = 0; i < 8; i++) {
        if (!m_registers[i]) {
            m_registers[i] = true;
            return i;
        }
    }
    throw std::runtime_error("No available registers");
}

void CodeGenerator::freeRegister(int reg) {
    if (reg >= 0 && reg < 8) {
        m_registers[reg] = false;
    }
}

void CodeGenerator::pushRegister(int reg) {
    emit("    push R" + std::to_string(reg));
}

void CodeGenerator::popRegister(int reg) {
    emit("    pop R" + std::to_string(reg));
}

int CodeGenerator::evaluateExpression(Expr& expr) {
    // 简化的表达式求值
    if (expr.type == ASTNodeType::INTEGER_LITERAL) {
        auto& literal = static_cast<IntegerLiteral&>(expr);
        return literal.value;
    }
    if (expr.type == ASTNodeType::CHAR_LITERAL) {
        auto& literal = static_cast<CharLiteral&>(expr);
        return static_cast<int>(literal.value);
    }
    if (expr.type == ASTNodeType::BINARY_EXPR) {
        auto& binary = static_cast<BinaryExpr&>(expr);
        int left = evaluateExpression(*binary.left);
        int right = evaluateExpression(*binary.right);
        if (binary.op == "+") return left + right;
        if (binary.op == "-") return left - right;
        if (binary.op == "*") return left * right;
        if (binary.op == "/") return left / right;
        if (binary.op == "%") return left % right;
        throw std::runtime_error("Unsupported binary operator in compile-time evaluation: " + binary.op);
    }
    if (expr.type == ASTNodeType::UNARY_EXPR) {
        auto& unary = static_cast<UnaryExpr&>(expr);
        int operand = evaluateExpression(*unary.operand);
        if (unary.op == "-") return -operand;
        if (unary.op == "!") return !operand;
        throw std::runtime_error("Unsupported unary operator in compile-time evaluation: " + unary.op);
    }
    throw std::runtime_error("Cannot evaluate expression at compile time");
}

std::string CodeGenerator::getType(Expr& expr) {
    // 简化的类型推断
    switch (expr.type) {
        case ASTNodeType::INTEGER_LITERAL:
            return "int";
        case ASTNodeType::CHAR_LITERAL:
            return "char";
        case ASTNodeType::IDENTIFIER_EXPR: {
            auto& identifier = static_cast<IdentifierExpr&>(expr);
            auto it = m_symbolTable.find(identifier.name);
            if (it != m_symbolTable.end()) {
                return it->second.type;
            }
            throw std::runtime_error("Undefined variable: " + identifier.name);
        }
        default:
            return "int"; // 默认类型
    }
}

void CodeGenerator::visit(Program& node) {
    // 生成程序头
    emit("; NanoC Generated Assembly");
    emit("; Generated by ncc compiler");
    emit("");
    
    // 访问所有声明
    for (auto& decl : node.declarations) {
        decl->accept(*this);
    }
    
    // 如果没有main函数，添加一个默认的
    if (m_symbolTable.find("main") == m_symbolTable.end()) {
        emit("");
        emit("; Default main function");
        emit("main:");
        emit("    trap 2"); // HALT
    }
}

void CodeGenerator::visit(VarDeclaration& node) {
    // 在符号表中添加变量
    Symbol symbol;
    symbol.name = node.name;
    symbol.type = node.type;
    symbol.offset = m_currentOffset;
    m_symbolTable[node.name] = symbol;
    
    // 分配栈空间
    m_currentOffset += 4; // 假设所有变量都是4字节
    
    // 如果有初始化表达式
    if (node.initializer) {
        // 计算初始化值
        int value = evaluateExpression(*node.initializer);
        
        // 生成初始化代码
        emit("    ; Initialize variable " + node.name);
        emit("    lmm R0, " + std::to_string(value));
        emit("    st R0, [BP-" + std::to_string(symbol.offset) + "]");
    }
}

void CodeGenerator::visit(FuncDeclaration& node) {
    // 保存当前作用域
    pushScope();
    
    // 重置栈偏移
    int savedOffset = m_currentOffset;
    m_currentOffset = 0;
    
    // 在符号表中添加函数
    Symbol funcSymbol;
    funcSymbol.name = node.name;
    funcSymbol.type = node.returnType;
    funcSymbol.offset = 0;
    m_symbolTable[node.name] = funcSymbol;
    
    // 生成函数标签
    emit("");
    emit("; Function: " + node.name);
    emit(node.name + ":");
    
    // 生成函数序言
    emit("    ; Function prologue");
    emit("    push BP");
    emit("    lmm BP, SP");
    
    // 为参数分配空间
    for (size_t i = 0; i < node.parameters.size(); i++) {
        auto& param = node.parameters[i];
        Symbol paramSymbol;
        paramSymbol.name = param->name;
        paramSymbol.type = param->type;
        paramSymbol.offset = m_currentOffset + 4; // 参数在返回地址之上
        m_symbolTable[param->name] = paramSymbol;
        m_currentOffset += 4;
    }
    
    // 为局部变量预留空间（简化处理）
    emit("    sub SP, 100"); // 预留100字节空间
    
    // 访问函数体
    if (node.body) {
        node.body->accept(*this);
    }
    
    // 生成函数尾声
    emit("    ; Function epilogue");
    emit("    lmm SP, BP");
    emit("    pop BP");
    emit("    ret");
    
    // 恢复作用域
    m_currentOffset = savedOffset;
    popScope();
}

void CodeGenerator::visit(CompoundStmt& node) {
    pushScope();
    
    for (auto& stmt : node.statements) {
        stmt->accept(*this);
    }
    
    popScope();
}

void CodeGenerator::visit(IfStmt& node) {
    std::string elseLabel = newLabel();
    std::string endLabel = newLabel();
    
    // 生成条件表达式
    node.condition->accept(*this);
    
    // 条件跳转
    emit("    ; If statement");
    emit("    pop R0");
    emit("    eq R0, 0");
    emit("    jic " + elseLabel);
    
    // then分支
    if (node.thenBranch) {
        node.thenBranch->accept(*this);
    }
    emit("    jmp " + endLabel);
    
    // else分支
    emitLabel(elseLabel);
    if (node.elseBranch) {
        node.elseBranch->accept(*this);
    }
    
    emitLabel(endLabel);
}

void CodeGenerator::visit(WhileStmt& node) {
    std::string loopLabel = newLabel();
    std::string endLabel = newLabel();
    
    // 保存break和continue标签
    m_breakLabels.push_back(endLabel);
    m_continueLabels.push_back(loopLabel);
    
    emitLabel(loopLabel);
    
    // 生成条件表达式
    node.condition->accept(*this);
    
    // 条件跳转
    emit("    ; While loop");
    emit("    pop R0");
    emit("    eq R0, 0");
    emit("    jic " + endLabel);
    
    // 循环体
    if (node.body) {
        node.body->accept(*this);
    }
    
    // 跳回循环开始
    emit("    jmp " + loopLabel);
    
    emitLabel(endLabel);
    
    // 恢复break和continue标签
    m_breakLabels.pop_back();
    m_continueLabels.pop_back();
}

void CodeGenerator::visit(ForStmt& node) {
    std::string loopLabel = newLabel();
    std::string continueLabel = newLabel();
    std::string endLabel = newLabel();
    
    // 保存break和continue标签
    m_breakLabels.push_back(endLabel);
    m_continueLabels.push_back(continueLabel);
    
    // 初始化部分
    if (node.init) {
        node.init->accept(*this);
    }
    
    emitLabel(loopLabel);
    
    // 条件部分
    if (node.condition) {
        node.condition->accept(*this);
        emit("    ; For loop condition");
        emit("    pop R0");
        emit("    eq R0, 0");
        emit("    jic " + endLabel);
    }
    
    // 循环体
    if (node.body) {
        node.body->accept(*this);
    }
    
    emitLabel(continueLabel);
    
    // 增量部分
    if (node.increment) {
        node.increment->accept(*this);
    }
    
    // 跳回循环开始
    emit("    jmp " + loopLabel);
    
    emitLabel(endLabel);
    
    // 恢复break和continue标签
    m_breakLabels.pop_back();
    m_continueLabels.pop_back();
}

void CodeGenerator::visit(ReturnStmt& node) {
    emit("    ; Return statement");
    
    if (node.value) {
        // 计算返回值
        node.value->accept(*this);
        emit("    pop R0"); // 返回值在R0中
    }
    
    // 函数尾声
    emit("    lmm SP, BP");
    emit("    pop BP");
    emit("    ret");
}

void CodeGenerator::visit(BreakStmt& node) {
    if (m_breakLabels.empty()) {
        throw std::runtime_error("break statement not within loop");
    }
    
    emit("    ; Break statement");
    emit("    jmp " + m_breakLabels.back());
}

void CodeGenerator::visit(ContinueStmt& node) {
    if (m_continueLabels.empty()) {
        throw std::runtime_error("continue statement not within loop");
    }
    
    emit("    ; Continue statement");
    emit("    jmp " + m_continueLabels.back());
}

void CodeGenerator::visit(ExprStmt& node) {
    if (node.expression) {
        node.expression->accept(*this);
        // 表达式语句的结果通常被丢弃
        emit("    pop R0");
    }
}

void CodeGenerator::visit(BinaryExpr& node) {
    // 计算左操作数
    node.left->accept(*this);
    
    // 计算右操作数
    node.right->accept(*this);
    
    // 弹出操作数
    emit("    pop R1"); // 右操作数
    emit("    pop R0"); // 左操作数
    
    // 执行运算
    emit("    ; Binary operation: " + node.op);
    
    if (node.op == "+") {
        emit("    add R0, R1");
    } else if (node.op == "-") {
        emit("    sub R0, R1");
    } else if (node.op == "*") {
        emit("    mul R0, R1");
    } else if (node.op == "/") {
        emit("    div R0, R1");
    } else if (node.op == "%") {
        emit("    mod R0, R1");
    } else if (node.op == "==") {
        emit("    eq R0, R1");
    } else if (node.op == "!=") {
        emit("    ne R0, R1");
    } else if (node.op == "<") {
        emit("    lt R0, R1");
    } else if (node.op == "<=") {
        emit("    le R0, R1");
    } else if (node.op == ">") {
        emit("    gt R0, R1");
    } else if (node.op == ">=") {
        emit("    ge R0, R1");
    } else if (node.op == "&&") {
        emit("    and R0, R1");
    } else if (node.op == "||") {
        emit("    or R0, R1");
    } else {
        throw std::runtime_error("Unknown binary operator: " + node.op);
    }
    
    // 将结果压栈
    emit("    push R0");
}

void CodeGenerator::visit(UnaryExpr& node) {
    // 计算操作数
    node.operand->accept(*this);
    
    // 弹出操作数
    emit("    pop R0");
    
    // 执行运算
    emit("    ; Unary operation: " + node.op);
    
    if (node.op == "-") {
        emit("    mul R0, -1");
    } else if (node.op == "!") {
        emit("    not R0");
    } else {
        throw std::runtime_error("Unknown unary operator: " + node.op);
    }
    
    // 将结果压栈
    emit("    push R0");
}

void CodeGenerator::visit(AssignExpr& node) {
    // 计算右值
    node.value->accept(*this);
    
    // 弹出右值
    emit("    pop R0");
    
    // 查找变量
    auto it = m_symbolTable.find(node.name);
    if (it == m_symbolTable.end()) {
        throw std::runtime_error("Undefined variable: " + node.name);
    }
    
    // 存储到变量
    emit("    ; Assignment to " + node.name);
    emit("    st R0, [BP-" + std::to_string(it->second.offset) + "]");
    
    // 将结果压栈（赋值表达式的值）
    emit("    push R0");
}

void CodeGenerator::visit(CallExpr& node) {
    emit("    ; Function call: " + node.callee);
    
    // 保存当前寄存器状态（简化处理）
    
    // 压入参数（从右到左）
    for (auto it = node.arguments.rbegin(); it != node.arguments.rend(); ++it) {
        (*it)->accept(*this);
    }
    
    // 调用函数
    emit("    call " + node.callee);
    
    // 清理参数（简化处理，假设调用者清理）
    if (!node.arguments.empty()) {
        emit("    add SP, " + std::to_string(node.arguments.size() * 4));
    }
    
    // 返回值在R0中，压栈
    emit("    push R0");
}

void CodeGenerator::visit(IdentifierExpr& node) {
    // 查找变量
    auto it = m_symbolTable.find(node.name);
    if (it == m_symbolTable.end()) {
        throw std::runtime_error("Undefined variable: " + node.name);
    }
    
    // 加载变量值
    emit("    ; Load variable " + node.name);
    emit("    lea R0, [BP-" + std::to_string(it->second.offset) + "]");
    emit("    push R0");
}

void CodeGenerator::visit(IntegerLiteral& node) {
    emit("    ; Integer literal: " + std::to_string(node.value));
    emit("    lmm R0, " + std::to_string(node.value));
    emit("    push R0");
}

void CodeGenerator::visit(CharLiteral& node) {
    emit("    ; Char literal: '" + std::string(1, node.value) + "'");
    emit("    lmm R0, " + std::to_string(static_cast<int>(node.value)));
    emit("    push R0");
}

void CodeGenerator::visit(StmtVarDeclaration& node) {
    // 在符号表中添加变量
    Symbol symbol;
    symbol.name = node.name;
    symbol.type = node.type;
    symbol.offset = m_currentOffset;
    m_symbolTable[node.name] = symbol;
    
    // 分配栈空间
    m_currentOffset += 4; // 假设所有变量都是4字节
    
    // 如果有初始化表达式
    if (node.initializer) {
        // 计算初始化值
        int value = evaluateExpression(*node.initializer);
        
        // 生成初始化代码
        emit("    ; Initialize variable " + node.name);
        emit("    lmm R0, " + std::to_string(value));
        emit("    st R0, [BP-" + std::to_string(symbol.offset) + "]");
    }
}