#include "ncc/codegen.hpp"
#include <algorithm>
#include <stdexcept>

namespace {

    // 规范类型名后缀工具：基型（int/char/void/struct Tag）+ 指针星号 + 数组方括号
    bool endsWith(const std::string& s, const std::string& suffix) {
        return s.size() >= suffix.size()
               && s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
    }

    std::string stripSuffix(const std::string& s, const std::string& suffix) {
        if (endsWith(s, suffix)) {
            return s.substr(0, s.size() - suffix.size());
        }
        return s;
    }

    bool isPointerTypeName(const std::string& t) { return endsWith(t, "*"); }

    bool isArrayTypeName(const std::string& t) { return endsWith(t, "[]"); }

    std::string pointerPointee(const std::string& t) { return stripSuffix(t, "*"); }

    std::string arrayElement(const std::string& t) { return stripSuffix(t, "[]"); }

    // 数组名在值上下文退化为指针
    std::string decayedTypeName(const std::string& t) {
        if (isArrayTypeName(t)) {
            return arrayElement(t) + "*";
        }
        return t;
    }

} // namespace

CodeGenerator::CodeGenerator() { m_sink = &m_code; }

std::string CodeGenerator::generate(Program& program) {
    m_code.clear();
    m_data.clear();
    m_labelCounter = 0;
    m_functions.clear();
    m_globalSymbols.clear();
    m_localSymbols.clear();
    m_globalOrder.clear();
    m_globalInits.clear();
    m_registeredGlobals.clear();
    m_externs.clear();
    m_externSet.clear();
    m_stringLiterals.clear();
    m_functionReturns.clear();
    m_breakLabels.clear();
    m_continueLabels.clear();
    m_nextSlot = 0;
    m_structs.clear();
    m_typedefs.clear();
    m_structReturnTag.clear();
    m_sretSaveSlot = 0;
    m_tempCursor = 0;
    m_tempLimit = 0;
    m_sink = &m_code;

    program.accept(*this);

    // 拼装：头注释 + extern 指令 + 函数体 + 数据段
    std::string output;
    output += "; NanoC Generated Assembly (NCI v2.1)\n";
    output += "; Generated by ncc compiler\n\n";
    for (const auto& name : m_externs) {
        output += "extern " + name + "\n";
    }
    if (!m_externs.empty()) {
        output += "\n";
    }
    output += m_code;
    output += m_data;
    return output;
}

void CodeGenerator::emit(const std::string& code) { *m_sink += code + "\n"; }

void CodeGenerator::emitLabel(const std::string& label) { *m_sink += label + ":\n"; }

std::string CodeGenerator::newLabel() { return "L" + std::to_string(m_labelCounter++); }

const CodeGenerator::Symbol* CodeGenerator::findSymbol(const std::string& name) const {
    auto local = m_localSymbols.find(name);
    if (local != m_localSymbols.end()) {
        return &local->second;
    }
    auto global = m_globalSymbols.find(name);
    if (global != m_globalSymbols.end()) {
        return &global->second;
    }
    return nullptr;
}

// ---- 类型解析（typedef/struct 透明展开） ----

// 声明里的基础类型名 → 规范基型："int"/"char"/"void"/"struct Tag"
std::string CodeGenerator::resolveBaseType(const std::string& name,
                                           bool isStructTag) const {
    if (isStructTag) {
        return "struct " + name;
    }
    if (name == "int" || name == "char" || name == "void") {
        return name;
    }
    auto it = m_typedefs.find(name);
    if (it != m_typedefs.end()) {
        return it->second; // 别名透明展开（可能已含指针后缀）
    }
    return name; // 未知类型：语义分析已报错，此处原样保留
}

std::string CodeGenerator::canonicalType(const std::string& base,
                                         int pointerDepth,
                                         bool isArray) const {
    if (isArray) {
        return base + "[]";
    }
    if (pointerDepth >= 1) {
        return base + "*";
    }
    return base;
}

// "struct T"（值形态）→ 布局表条目；其余返回 nullptr
const CodeGenerator::StructLayout*
CodeGenerator::structLayoutOf(const std::string& type) const {
    if (type.rfind("struct ", 0) != 0 || isPointerTypeName(type)
        || isArrayTypeName(type)) {
        return nullptr;
    }
    auto it = m_structs.find(type.substr(7));
    return it != m_structs.end() ? &it->second : nullptr;
}

const CodeGenerator::StructLayout*
CodeGenerator::findFieldLayout(const std::string& type) const {
    return structLayoutOf(type);
}

const CodeGenerator::FieldLayout*
CodeGenerator::findField(const StructLayout& layout, const std::string& name) const {
    for (const auto& field : layout.fields) {
        if (field.name == name) {
            return &field;
        }
    }
    return nullptr;
}

// struct 定义 → 布局表（与 semantic 同一规则：按声明顺序累加、4 字节对齐无填充）
void CodeGenerator::registerStructLayout(const StructDeclaration& node) {
    if (node.isForward) {
        if (m_structs.find(node.tag) == m_structs.end()) {
            m_structs[node.tag] = StructLayout{};
        }
        return;
    }
    auto existing = m_structs.find(node.tag);
    if (existing != m_structs.end() && existing->second.complete) {
        return; // 重复定义：语义分析已报错
    }

    StructLayout layout;
    int offsetWords = 0;
    for (const auto& field : node.fields) {
        const std::string base = resolveBaseType(field->type, field->isStructTag);
        const std::string fieldType =
          canonicalType(base, field->pointerDepth, field->isArray);
        int sizeWords = 1;
        if (field->isArray) {
            const std::string element = arrayElement(fieldType);
            sizeWords = std::max(field->arraySize, 1) * typeSizeWords(element);
        } else {
            sizeWords = typeSizeWords(fieldType);
        }
        FieldLayout entry;
        entry.name = field->name;
        entry.offsetWords = offsetWords;
        entry.sizeWords = std::max(sizeWords, 1);
        entry.type = fieldType;
        offsetWords += entry.sizeWords;
        layout.fields.push_back(std::move(entry));
    }
    layout.sizeWords = offsetWords;
    layout.complete = !layout.fields.empty();
    m_structs[node.tag] = std::move(layout);
}

// 类型字数：标量/指针 1，struct 值按布局；数组/未知类型由调用方另行处理
int CodeGenerator::typeSizeWords(const std::string& type) const {
    if (const StructLayout* layout = structLayoutOf(type)) {
        return std::max(layout->sizeWords, 1);
    }
    if (isPointerTypeName(type) || isArrayTypeName(type)) {
        return 1;
    }
    if (type == "int" || type == "char" || type == "void") {
        return 1;
    }
    return 1; // 未知类型占位（语义分析已报错）
}

// ---- 全局变量 ----

void CodeGenerator::registerGlobal(VarDeclaration& node) {
    if (!m_registeredGlobals.insert(&node).second) {
        return; // 同一声明只登记一次
    }
    if (m_globalSymbols.find(node.name) == m_globalSymbols.end()) {
        m_globalOrder.push_back(node.name);
    }
    Symbol symbol;
    symbol.kind = SymKind::Global;
    symbol.label = ".g_" + node.name;
    symbol.type = canonicalType(resolveBaseType(node.type, node.isStructTag),
                                node.pointerDepth,
                                node.isArray);
    symbol.isArray = node.isArray;
    symbol.arraySize = node.arraySize;
    m_globalSymbols[node.name] = symbol;

    if (!node.initializer) {
        return;
    }
    if (node.initializer->type == ASTNodeType::INIT_LIST_EXPR) {
        // struct 逐成员初始化器：每个标量/指针成员一条全局初始化
        auto& initList = static_cast<InitListExpr&>(*node.initializer);
        const StructLayout* layout = structLayoutOf(symbol.type);
        if (layout == nullptr) {
            throw std::runtime_error("array initializers are not supported");
        }
        for (size_t i = 0; i < initList.values.size() && i < layout->fields.size(); ++i) {
            if (initList.values[i]->type == ASTNodeType::INIT_LIST_EXPR) {
                throw std::runtime_error("nested initializers are not supported");
            }
            GlobalInit init;
            init.label = symbol.label;
            init.offsetWords = layout->fields[i].offsetWords;
            init.expr = initList.values[i].get();
            m_globalInits.push_back(init);
        }
        return;
    }
    // 数组整体初始化被语义拒绝；此处防御式跳过
    if (!node.isArray) {
        GlobalInit init;
        init.label = symbol.label;
        init.offsetWords = 0;
        init.expr = node.initializer.get();
        m_globalInits.push_back(init);
    }
}

void CodeGenerator::emitGlobalInits() {
    for (const auto& init : m_globalInits) {
        init.expr->accept(*this); // 求值结果压栈
        emit("    pop R0");
        emit("    lea R6, " + init.label);
        if (init.offsetWords > 0) {
            emit("    addi R6, " + std::to_string(4 * init.offsetWords));
        }
        emit("    store [R6], R0");
    }
}

// ---- 变量读写 ----

void CodeGenerator::emitLoadVar(const Symbol& sym) {
    switch (sym.kind) {
    case SymKind::Local:
        emit("    mov R6, R5");
        emit("    subi R6, " + std::to_string(4 * sym.slot));
        emit("    load R0, [R6]");
        break;
    case SymKind::StackArg:
        emit("    mov R6, R5");
        emit("    addi R6, " + std::to_string(4 * (sym.argIndex - 3)));
        emit("    load R0, [R6]");
        break;
    case SymKind::Global:
        emit("    lea R6, " + sym.label);
        emit("    load R0, [R6]");
        break;
    }
}

void CodeGenerator::emitStoreVar(const Symbol& sym) {
    switch (sym.kind) {
    case SymKind::Local:
        emit("    mov R6, R5");
        emit("    subi R6, " + std::to_string(4 * sym.slot));
        break;
    case SymKind::StackArg:
        emit("    mov R6, R5");
        emit("    addi R6, " + std::to_string(4 * (sym.argIndex - 3)));
        break;
    case SymKind::Global:
        emit("    lea R6, " + sym.label);
        break;
    }
    emit("    store [R6], R0");
}

// struct 对象地址 → R0：形参槽位存副本地址（load 即得），局部/全局取槽地址
void CodeGenerator::emitStructAddressOfSymbol(const Symbol& sym) {
    if (sym.isStructParam) {
        emitLoadVar(sym);
        return;
    }
    emitAddressOfSymbol(sym);
}

// ---- 条件分支 ----

void CodeGenerator::emitTestBranch(const std::string& target, bool branchOnTrue) {
    // TEST R, R：按位 AND 置 flags（0 → Z，负 → N，正 → P）
    emit("    test R0, R0");
    emit(std::string("    ") + (branchOnTrue ? "jnz " : "jz ") + target);
}

void CodeGenerator::emitCompareBranch(const std::string& op,
                                      const std::string& target,
                                      bool branchOnTrue) {
    // flags 由 CMP 置位：Z = 相等、N = 左 < 右、P = 左 > 右
    // 无 JNN/JNP，Z|N / Z|P 类条件用两次跳转复合
    emit("    cmp R0, R1");
    auto jump = [&](const std::string& mnemonic) {
        emit("    " + mnemonic + " " + target);
    };
    if (op == "==") {
        branchOnTrue ? jump("jz") : jump("jnz");
    } else if (op == "!=") {
        branchOnTrue ? jump("jnz") : jump("jz");
    } else if (op == "<") {
        branchOnTrue ? jump("jn") : (jump("jz"), jump("jp"));
    } else if (op == "<=") {
        branchOnTrue ? (jump("jz"), jump("jn")) : jump("jp");
    } else if (op == ">") {
        branchOnTrue ? jump("jp") : (jump("jz"), jump("jn"));
    } else if (op == ">=") {
        branchOnTrue ? (jump("jz"), jump("jp")) : jump("jn");
    } else {
        throw std::runtime_error("Unknown comparison operator: " + op);
    }
}

void CodeGenerator::emitCompareValue(const std::string& op) {
    // 比较作为表达式值时物化为 0/1：条件成立 → 1，否则 → 0
    const std::string trueLabel = newLabel();
    const std::string endLabel = newLabel();
    emit("    cmp R0, R1");
    if (op == "==") {
        emit("    jz " + trueLabel);
    } else if (op == "!=") {
        emit("    jnz " + trueLabel);
    } else if (op == "<") {
        emit("    jn " + trueLabel);
    } else if (op == "<=") {
        emit("    jz " + trueLabel);
        emit("    jn " + trueLabel);
    } else if (op == ">") {
        emit("    jp " + trueLabel);
    } else if (op == ">=") {
        emit("    jz " + trueLabel);
        emit("    jp " + trueLabel);
    } else {
        throw std::runtime_error("Unknown comparison operator: " + op);
    }
    emit("    lmm R2, 0");
    emit("    jmp " + endLabel);
    emitLabel(trueLabel);
    emit("    lmm R2, 1");
    emitLabel(endLabel);
    emit("    push R2");
}

void CodeGenerator::emitBranchFalse(Expr& expr, const std::string& target) {
    emitBranch(expr, target, false);
}

void CodeGenerator::emitBranchTrue(Expr& expr, const std::string& target) {
    emitBranch(expr, target, true);
}

void CodeGenerator::emitBranch(Expr& expr, const std::string& target, bool branchOnTrue) {
    if (expr.type == ASTNodeType::BINARY_EXPR) {
        auto& binary = static_cast<BinaryExpr&>(expr);
        if (binary.op == "&&") {
            // 左假即假；左右皆真才为真
            if (branchOnTrue) {
                const std::string falseLabel = newLabel();
                emitBranchFalse(*binary.left, falseLabel);
                emitBranchTrue(*binary.right, target);
                emitLabel(falseLabel);
            } else {
                emitBranchFalse(*binary.left, target);
                emitBranchFalse(*binary.right, target);
            }
            return;
        }
        if (binary.op == "||") {
            // 左真即真；左右皆假才为假
            if (branchOnTrue) {
                emitBranchTrue(*binary.left, target);
                emitBranchTrue(*binary.right, target);
            } else {
                const std::string trueLabel = newLabel();
                emitBranchTrue(*binary.left, trueLabel);
                emitBranchFalse(*binary.right, target);
                emitLabel(trueLabel);
            }
            return;
        }
        if (binary.op == "==" || binary.op == "!=" || binary.op == "<"
            || binary.op == "<=" || binary.op == ">" || binary.op == ">=") {
            binary.left->accept(*this);
            binary.right->accept(*this);
            emit("    pop R1");
            emit("    pop R0");
            emitCompareBranch(binary.op, target, branchOnTrue);
            return;
        }
    }
    if (expr.type == ASTNodeType::UNARY_EXPR) {
        auto& unary = static_cast<UnaryExpr&>(expr);
        if (unary.op == "!") {
            emitBranch(*unary.operand, target, !branchOnTrue);
            return;
        }
    }
    // 其余表达式：求值后按真值跳转
    expr.accept(*this);
    emit("    pop R0");
    emitTestBranch(target, branchOnTrue);
}

// ---- 函数帧统计 ----

int CodeGenerator::countLocalSlots(Stmt* stmt) const {
    if (!stmt) {
        return 0;
    }
    switch (stmt->type) {
    case ASTNodeType::COMPOUND_STMT: {
        auto& compound = static_cast<CompoundStmt&>(*stmt);
        int count = 0;
        for (auto& child : compound.statements) {
            count += countLocalSlots(child.get());
        }
        return count;
    }
    case ASTNodeType::VAR_DECLARATION: { // 语句上下文的声明节点（StmtVarDeclaration）
        auto& varDecl = static_cast<StmtVarDeclaration&>(*stmt);
        // struct 值按布局字数占槽；数组按元素数 × 元素字数
        const std::string type =
          canonicalType(resolveBaseType(varDecl.type, varDecl.isStructTag),
                        varDecl.pointerDepth,
                        varDecl.isArray);
        int words = typeSizeWords(type);
        if (varDecl.isArray) {
            // 数组元素类型 = 去掉 "[]" 后缀（struct 元素按布局字数）
            const std::string element = arrayElement(type);
            words = std::max(varDecl.arraySize, 1) * typeSizeWords(element);
        }
        return std::max(words, 1);
    }
    case ASTNodeType::IF_STMT: {
        auto& ifStmt = static_cast<IfStmt&>(*stmt);
        return countLocalSlots(ifStmt.thenBranch.get())
               + countLocalSlots(ifStmt.elseBranch.get());
    }
    case ASTNodeType::WHILE_STMT:
        return countLocalSlots(static_cast<WhileStmt&>(*stmt).body.get());
    case ASTNodeType::FOR_STMT: {
        auto& forStmt = static_cast<ForStmt&>(*stmt);
        return countLocalSlots(forStmt.init.get()) + countLocalSlots(forStmt.body.get());
    }
    default:
        return 0;
    }
}

// ---- struct 临时空间统计 ----

// 表达式子树需要的 struct 临时词数：struct 返回调用的接收槽 +
// struct 值实参的副本槽
int CodeGenerator::structTempWords(const Expr* expr) {
    if (!expr) {
        return 0;
    }
    switch (expr->type) {
    case ASTNodeType::CALL_EXPR: {
        auto& call = static_cast<const CallExpr&>(*expr);
        int words = 0;
        auto it = m_functionReturns.find(call.callee);
        const std::string returnType = it != m_functionReturns.end() ? it->second : "int";
        if (const StructLayout* layout = structLayoutOf(returnType)) {
            words += std::max(layout->sizeWords, 1);
        }
        for (const auto& argument : call.arguments) {
            words += structTempWords(argument.get());
            const std::string argumentType = exprType(*argument);
            if (const StructLayout* argumentLayout = structLayoutOf(argumentType)) {
                words += std::max(argumentLayout->sizeWords, 1);
            }
        }
        return words;
    }
    case ASTNodeType::BINARY_EXPR: {
        auto& binary = static_cast<const BinaryExpr&>(*expr);
        return structTempWords(binary.left.get()) + structTempWords(binary.right.get());
    }
    case ASTNodeType::UNARY_EXPR:
        return structTempWords(static_cast<const UnaryExpr&>(*expr).operand.get());
    case ASTNodeType::ASSIGN_EXPR: {
        auto& assign = static_cast<const AssignExpr&>(*expr);
        return structTempWords(assign.target.get()) + structTempWords(assign.value.get());
    }
    case ASTNodeType::INDEX_EXPR: {
        auto& index = static_cast<const IndexExpr&>(*expr);
        return structTempWords(index.base.get()) + structTempWords(index.index.get());
    }
    case ASTNodeType::MEMBER_EXPR:
        return structTempWords(static_cast<const MemberExpr&>(*expr).base.get());
    case ASTNodeType::INIT_LIST_EXPR: {
        int words = 0;
        for (const auto& value : static_cast<const InitListExpr&>(*expr).values) {
            words += structTempWords(value.get());
        }
        return words;
    }
    default:
        return 0;
    }
}

// 语句树：登记局部变量类型（exprType 计数依赖符号类型，须先于函数体生成），
// 并累计 struct 临时词数
int CodeGenerator::countStructTemps(const Stmt* stmt) {
    if (!stmt) {
        return 0;
    }
    switch (stmt->type) {
    case ASTNodeType::COMPOUND_STMT: {
        int words = 0;
        for (const auto& child : static_cast<const CompoundStmt&>(*stmt).statements) {
            words += countStructTemps(child.get());
        }
        return words;
    }
    case ASTNodeType::VAR_DECLARATION: {
        const auto& varDecl = static_cast<const StmtVarDeclaration&>(*stmt);
        // 登记局部变量类型（槽位在函数体生成时正式分配，此处类型即所需）
        Symbol symbol;
        symbol.kind = SymKind::Local;
        symbol.type = canonicalType(resolveBaseType(varDecl.type, varDecl.isStructTag),
                                    varDecl.pointerDepth,
                                    varDecl.isArray);
        symbol.isArray = varDecl.isArray;
        symbol.arraySize = varDecl.arraySize;
        m_localSymbols[varDecl.name] = symbol;
        return varDecl.initializer ? structTempWords(varDecl.initializer.get()) : 0;
    }
    case ASTNodeType::IF_STMT: {
        auto& ifStmt = static_cast<const IfStmt&>(*stmt);
        return structTempWords(ifStmt.condition.get())
               + countStructTemps(ifStmt.thenBranch.get())
               + countStructTemps(ifStmt.elseBranch.get());
    }
    case ASTNodeType::WHILE_STMT: {
        auto& whileStmt = static_cast<const WhileStmt&>(*stmt);
        return structTempWords(whileStmt.condition.get())
               + countStructTemps(whileStmt.body.get());
    }
    case ASTNodeType::FOR_STMT: {
        auto& forStmt = static_cast<const ForStmt&>(*stmt);
        return countStructTemps(forStmt.init.get())
               + structTempWords(forStmt.condition.get())
               + structTempWords(forStmt.increment.get())
               + countStructTemps(forStmt.body.get());
    }
    case ASTNodeType::RETURN_STMT:
        return structTempWords(static_cast<const ReturnStmt&>(*stmt).value.get());
    case ASTNodeType::EXPR_STMT:
        return structTempWords(static_cast<const ExprStmt&>(*stmt).expression.get());
    default:
        return 0;
    }
}

// ---- struct 临时槽与拷贝 ----

int CodeGenerator::allocStructTemp(int sizeWords) {
    if (m_tempCursor + sizeWords > m_tempLimit) {
        throw std::runtime_error("internal error: struct temporary slots exhausted");
    }
    // 块占 [cursor+1 .. cursor+sizeWords] 号槽；返回最高槽号作为基址
    // （与栈布局一致：地址 BP-4*槽号，槽号越大地址越低，拷贝向高地址延伸）
    m_tempCursor += sizeWords;
    return m_tempCursor;
}

// R1=源地址、R2=目的地址 → 逐字拷贝 sizeWords 字
void CodeGenerator::emitCopyWords(int sizeWords) {
    for (int i = 0; i < sizeWords; ++i) {
        emit("    mov R6, R1");
        if (i > 0) {
            emit("    addi R6, " + std::to_string(4 * i));
        }
        emit("    load R0, [R6]");
        emit("    mov R6, R2");
        if (i > 0) {
            emit("    addi R6, " + std::to_string(4 * i));
        }
        emit("    store [R6], R0");
    }
}

// 栈顶=源地址、R0=目的地址 → 逐字拷贝，push 目的地址（struct 赋值表达式的值）
void CodeGenerator::emitPopCopyPush(int sizeWords) {
    emit("    pop R1");     // 源地址（struct 值 = 地址）
    emit("    mov R2, R0"); // 目的地址
    emitCopyWords(sizeWords);
    emit("    mov R0, R2");
    emit("    push R0");
}

// 栈顶=源 struct 地址 → 拷贝到新临时槽，push 临时槽地址（struct 实参按值传递）
void CodeGenerator::emitStructArgCopy(const std::string& structType) {
    const StructLayout* layout = structLayoutOf(structType);
    const int sizeWords = layout != nullptr ? std::max(layout->sizeWords, 1) : 1;
    const int slot = allocStructTemp(sizeWords);
    emit("    mov R0, R5");
    emit("    subi R0, " + std::to_string(4 * slot)); // 目的地址
    emitPopCopyPush(sizeWords);
}

// ---- 访问者：程序与声明 ----

void CodeGenerator::visit(Program& node) {
    // 第一遍之一：struct 布局与 typedef 别名表（与 semantic 同序、同规则）
    for (auto& decl : node.declarations) {
        if (decl->type == ASTNodeType::STRUCT_DECLARATION) {
            registerStructLayout(static_cast<StructDeclaration&>(*decl));
        } else if (decl->type == ASTNodeType::TYPEDEF_DECLARATION) {
            auto& typedefDecl = static_cast<TypedefDeclaration&>(*decl);
            if (typedefDecl.structDef) {
                registerStructLayout(*typedefDecl.structDef);
            }
            const std::string base =
              resolveBaseType(typedefDecl.baseType, typedefDecl.baseIsStruct);
            m_typedefs[typedefDecl.alias] =
              canonicalType(base, typedefDecl.pointerDepth, false);
        }
    }

    // 第一遍之二：登记函数符号（允许前向引用）与全局变量
    for (auto& decl : node.declarations) {
        if (decl->type == ASTNodeType::FUNC_DECLARATION) {
            auto& func = static_cast<FuncDeclaration&>(*decl);
            m_functions.insert(func.name);
            m_functionReturns[func.name] =
              canonicalType(resolveBaseType(func.returnType, func.returnIsStruct),
                            func.returnPointerDepth,
                            false);
        } else if (decl->type == ASTNodeType::VAR_DECLARATION) {
            registerGlobal(static_cast<VarDeclaration&>(*decl));
        }
    }

    // 第二遍：逐函数生成
    bool hasMain = false;
    for (auto& decl : node.declarations) {
        if (decl->type != ASTNodeType::FUNC_DECLARATION) {
            continue;
        }
        auto& func = static_cast<FuncDeclaration&>(*decl);
        if (func.name == "main") {
            hasMain = true;
        }
        decl->accept(*this);
    }

    // 缺省 main：空函数，由 VM 栈底哨兵终止
    if (!hasMain) {
        emit("");
        emit("; Default main function");
        emitLabel("main");
        emit("    enter 0");
        emitGlobalInits();
        emit("    leave");
        emit("    ret");
    }

    // 数据段：全局变量/字符串字面量标号地址 = codeSize + 段内偏移（nas 统一编址回填）
    if (!m_globalOrder.empty() || !m_stringLiterals.empty()) {
        m_sink = &m_data;
        emit("");
        emit("; Data segment");
        // 全局变量：标量/指针 1 个字；数组按元素数；struct 按布局字数
        for (const auto& name : m_globalOrder) {
            const Symbol& symbol = m_globalSymbols.at(name);
            emitLabel(symbol.label);
            const std::string elementType =
              symbol.isArray ? arrayElement(symbol.type) : symbol.type;
            const int wordsPerElement = typeSizeWords(elementType);
            const int count = symbol.isArray ? std::max(symbol.arraySize, 1) : 1;
            const int words = wordsPerElement * count;
            for (int i = 0; i < words; ++i) {
                emit("    dd 0");
            }
        }
        // 字符串字面量：按字节打包 + 显式 NUL 终止（宿主 strlen 等按字节读）
        for (const auto& entry : m_stringLiterals) {
            emitLabel(entry.second);
            emit("    db \"" + entry.first + "\", 0");
        }
        m_sink = &m_code;
    }
}

void CodeGenerator::visit(VarDeclaration& node) {
    // 全局变量：只登记数据标号（已由 visit(Program) 预登记，此处兜底）
    registerGlobal(node);
}

void CodeGenerator::visit(StructDeclaration& node) {
    // 已由 visit(Program) 预登记布局（此处兜底）
    registerStructLayout(node);
}

void CodeGenerator::visit(TypedefDeclaration& node) {
    // 已由 visit(Program) 预登记别名（此处兜底）
    if (node.structDef) {
        registerStructLayout(*node.structDef);
    }
    const std::string base = resolveBaseType(node.baseType, node.baseIsStruct);
    m_typedefs[node.alias] = canonicalType(base, node.pointerDepth, false);
}

void CodeGenerator::visit(FuncDeclaration& node) {
    m_functions.insert(node.name);
    m_localSymbols.clear();
    m_nextSlot = 0;
    const bool isMain = (node.name == "main");

    const std::string returnType =
      m_functionReturns.count(node.name) > 0
        ? m_functionReturns.at(node.name)
        : canonicalType(resolveBaseType(node.returnType, node.returnIsStruct),
                        node.returnPointerDepth,
                        false);
    const StructLayout* returnLayout = structLayoutOf(returnType);
    const bool returnsStruct = returnLayout != nullptr;
    m_structReturnTag = returnsStruct ? returnType : std::string();

    emit("");
    emit("; Function: " + node.name);
    emitLabel(node.name);

    // fastcall：前 4 个参数占帧槽位（入口溢出保存），第 5 个起在调用者栈上。
    // struct 形参按地址传递：槽位存调用者副本地址（type 记为 struct T*）
    const int regParams = static_cast<int>(std::min<size_t>(node.parameters.size(), 4));
    for (int i = 0; i < regParams; ++i) {
        Symbol symbol;
        symbol.kind = SymKind::Local;
        symbol.slot = i + 1;
        symbol.type = canonicalType(
          resolveBaseType(node.parameters[i]->type, node.parameters[i]->isStructTag),
          node.parameters[i]->pointerDepth,
          false);
        if (structLayoutOf(symbol.type) != nullptr) {
            symbol.type += "*";
            symbol.isStructParam = true;
        }
        m_localSymbols[node.parameters[i]->name] = symbol;
    }
    for (size_t i = 4; i < node.parameters.size(); ++i) {
        Symbol symbol;
        symbol.kind = SymKind::StackArg;
        symbol.argIndex = static_cast<int>(i) + 1;
        symbol.type = canonicalType(
          resolveBaseType(node.parameters[i]->type, node.parameters[i]->isStructTag),
          node.parameters[i]->pointerDepth,
          false);
        if (structLayoutOf(symbol.type) != nullptr) {
            symbol.type += "*";
            symbol.isStructParam = true;
        }
        m_localSymbols[node.parameters[i]->name] = symbol;
    }
    m_nextSlot = regParams;

    // 帧布局：形参槽 + 局部槽 + struct 临时区（+ struct 返回的 R7 保存槽）
    const int localSlots = countLocalSlots(node.body.get());
    const int tempWords = countStructTemps(node.body.get());
    const int sretWords = returnsStruct ? 1 : 0;
    m_tempLimit = m_nextSlot + localSlots + tempWords + sretWords;
    m_tempCursor = m_nextSlot + localSlots;
    if (returnsStruct) {
        m_sretSaveSlot = allocStructTemp(1); // 1 字槽固定存调用者的 R7
    }

    const int enterSize = 4 * m_tempLimit;
    emit("    enter " + std::to_string(enterSize));

    // 溢出寄存器参数到帧槽位
    for (int i = 0; i < regParams; ++i) {
        emit("    mov R6, R5");
        emit("    subi R6, " + std::to_string(4 * (i + 1)));
        emit("    store [R6], R" + std::to_string(i));
    }

    // struct 返回：保存调用者传入的 R7（接收槽地址），防嵌套 struct 调用覆盖
    if (returnsStruct) {
        emit("    mov R6, R5");
        emit("    subi R6, " + std::to_string(4 * m_sretSaveSlot));
        emit("    store [R6], R7");
    }

    // main：先执行全局变量初始化（此时寄存器参数已溢出，可自由使用 R0/R6）
    if (isMain) {
        emitGlobalInits();
    }

    if (node.body) {
        node.body->accept(*this);
    }

    emit("    leave");
    emit("    ret");
    m_localSymbols.clear();
    m_structReturnTag.clear();
}

// ---- 语句 ----

void CodeGenerator::visit(CompoundStmt& node) {
    for (auto& stmt : node.statements) {
        stmt->accept(*this);
    }
}

void CodeGenerator::visit(IfStmt& node) {
    const std::string endLabel = newLabel();
    if (node.elseBranch) {
        const std::string elseLabel = newLabel();
        emitBranchFalse(*node.condition, elseLabel);
        if (node.thenBranch) {
            node.thenBranch->accept(*this);
        }
        emit("    jmp " + endLabel);
        emitLabel(elseLabel);
        node.elseBranch->accept(*this);
    } else {
        emitBranchFalse(*node.condition, endLabel);
        if (node.thenBranch) {
            node.thenBranch->accept(*this);
        }
    }
    emitLabel(endLabel);
}

void CodeGenerator::visit(WhileStmt& node) {
    const std::string loopLabel = newLabel();
    const std::string endLabel = newLabel();

    m_breakLabels.push_back(endLabel);
    m_continueLabels.push_back(loopLabel);

    emitLabel(loopLabel);
    emitBranchFalse(*node.condition, endLabel);
    if (node.body) {
        node.body->accept(*this);
    }
    emit("    jmp " + loopLabel);
    emitLabel(endLabel);

    m_breakLabels.pop_back();
    m_continueLabels.pop_back();
}

void CodeGenerator::visit(ForStmt& node) {
    const std::string loopLabel = newLabel();
    const std::string continueLabel = newLabel();
    const std::string endLabel = newLabel();

    m_breakLabels.push_back(endLabel);
    m_continueLabels.push_back(continueLabel);

    if (node.init) {
        node.init->accept(*this);
    }
    emitLabel(loopLabel);
    if (node.condition) {
        emitBranchFalse(*node.condition, endLabel);
    }
    if (node.body) {
        node.body->accept(*this);
    }
    emitLabel(continueLabel);
    if (node.increment) {
        node.increment->accept(*this);
    }
    emit("    jmp " + loopLabel);
    emitLabel(endLabel);

    m_breakLabels.pop_back();
    m_continueLabels.pop_back();
}

void CodeGenerator::visit(ReturnStmt& node) {
    if (node.value) {
        node.value->accept(*this);
        emit("    pop R0"); // 返回值统一在 R0
        if (!m_structReturnTag.empty()) {
            // sret：把返回的 struct（源地址在 R0）逐字拷到调用者接收槽 [保存的 R7]
            emit("    mov R1, R0"); // 源地址
            emit("    mov R6, R5");
            emit("    subi R6, " + std::to_string(4 * m_sretSaveSlot));
            emit("    load R2, [R6]"); // 目的地址 = 调用者接收槽
            emitCopyWords(typeSizeWords(m_structReturnTag));
            emit("    mov R0, R2"); // 约定 R0 = sret 接收槽地址
        }
    }
    emit("    leave");
    emit("    ret");
}

void CodeGenerator::visit(BreakStmt& node) {
    if (m_breakLabels.empty()) {
        throw std::runtime_error("break statement not within loop");
    }
    emit("    jmp " + m_breakLabels.back());
}

void CodeGenerator::visit(ContinueStmt& node) {
    if (m_continueLabels.empty()) {
        throw std::runtime_error("continue statement not within loop");
    }
    emit("    jmp " + m_continueLabels.back());
}

void CodeGenerator::visit(ExprStmt& node) {
    if (node.expression) {
        node.expression->accept(*this);
        emit("    pop R0"); // 表达式语句的结果被丢弃
    }
}

// ---- 表达式 ----

void CodeGenerator::visit(BinaryExpr& node) {
    if (node.op == "&&") {
        const std::string falseLabel = newLabel();
        const std::string endLabel = newLabel();
        emitBranchFalse(node, falseLabel);
        emit("    lmm R0, 1");
        emit("    push R0");
        emit("    jmp " + endLabel);
        emitLabel(falseLabel);
        emit("    lmm R0, 0");
        emit("    push R0");
        emitLabel(endLabel);
        return;
    }
    if (node.op == "||") {
        const std::string trueLabel = newLabel();
        const std::string endLabel = newLabel();
        emitBranchTrue(node, trueLabel);
        emit("    lmm R0, 0");
        emit("    push R0");
        emit("    jmp " + endLabel);
        emitLabel(trueLabel);
        emit("    lmm R0, 1");
        emit("    push R0");
        emitLabel(endLabel);
        return;
    }
    if (node.op == "==" || node.op == "!=" || node.op == "<" || node.op == "<="
        || node.op == ">" || node.op == ">=") {
        node.left->accept(*this);
        node.right->accept(*this);
        emit("    pop R1"); // 右操作数
        emit("    pop R0"); // 左操作数
        emitCompareValue(node.op);
        return;
    }

    // 算术运算：左操作数先压栈，右操作数在栈顶
    node.left->accept(*this);
    node.right->accept(*this);
    emit("    pop R1"); // 右操作数
    emit("    pop R0"); // 左操作数

    if (node.op == "+") {
        // 指针 ± 整数按指向类型大小缩放（标量/指针 4 字节，struct 按布局）
        const std::string lt = decayedTypeName(exprType(*node.left));
        const std::string rt = decayedTypeName(exprType(*node.right));
        if (isPointerTypeName(lt)) {
            emit("    lmm R2, " + std::to_string(4 * typeSizeWords(pointerPointee(lt))));
            emit("    mul R1, R2");
            emit("    add R0, R1");
        } else if (isPointerTypeName(rt)) {
            emit("    lmm R2, " + std::to_string(4 * typeSizeWords(pointerPointee(rt))));
            emit("    mul R0, R2");
            emit("    add R0, R1");
        } else {
            emit("    add R0, R1");
        }
    } else if (node.op == "-") {
        const std::string lt = decayedTypeName(exprType(*node.left));
        if (isPointerTypeName(lt)) {
            emit("    lmm R2, " + std::to_string(4 * typeSizeWords(pointerPointee(lt))));
            emit("    mul R1, R2");
        }
        emit("    sub R0, R1");
    } else if (node.op == "*") {
        emit("    mul R0, R1");
    } else if (node.op == "/") {
        emit("    div R0, R1");
    } else if (node.op == "%") {
        emit("    mod R0, R1");
    } else {
        throw std::runtime_error("Unknown binary operator: " + node.op);
    }
    emit("    push R0");
}

void CodeGenerator::visit(UnaryExpr& node) {
    if (node.op == "&") {
        // 取址：目标地址 → R0（仅左值，语义已校验）
        emitAddressOf(*node.operand);
        emit("    push R0");
        return;
    }
    if (node.op == "*") {
        // 解引用：操作数求值得地址；struct 指针解引用地址即 struct 值，不 LOAD
        node.operand->accept(*this);
        emit("    pop R0");
        const std::string operandType = decayedTypeName(exprType(*node.operand));
        if (isPointerTypeName(operandType)
            && structLayoutOf(pointerPointee(operandType)) == nullptr) {
            emit("    load R0, [R0]");
        }
        emit("    push R0");
        return;
    }

    node.operand->accept(*this);
    emit("    pop R0");

    if (node.op == "-") {
        emit("    neg R0");
        emit("    push R0");
    } else if (node.op == "!") {
        // 逻辑非：test 置 flags 后物化 0/1
        const std::string nonzeroLabel = newLabel();
        const std::string endLabel = newLabel();
        emit("    test R0, R0");
        emit("    jnz " + nonzeroLabel);
        emit("    lmm R2, 1");
        emit("    jmp " + endLabel);
        emitLabel(nonzeroLabel);
        emit("    lmm R2, 0");
        emitLabel(endLabel);
        emit("    push R2");
    } else {
        throw std::runtime_error("Unknown unary operator: " + node.op);
    }
}

void CodeGenerator::visit(AssignExpr& node) {
    node.value->accept(*this); // 值/源 struct 地址压栈

    switch (node.target->type) {
    case ASTNodeType::IDENTIFIER_EXPR: {
        const auto& ident = static_cast<IdentifierExpr&>(*node.target);
        const Symbol* symbol = findSymbol(ident.name);
        if (!symbol) {
            throw std::runtime_error("Undefined variable: " + ident.name);
        }
        if (isArrayTypeName(symbol->type)) {
            // 数组整体赋值已被语义拒绝；防御式报错
            throw std::runtime_error("Cannot assign to array: " + ident.name);
        }
        if (structLayoutOf(symbol->type) != nullptr) {
            // struct 整体赋值：逐字拷贝（栈顶=源地址）
            emitStructAddressOfSymbol(*symbol); // 目的地址 → R0
            emitPopCopyPush(typeSizeWords(symbol->type));
            return; // 已 push 赋值结果（目的地址）
        }
        emit("    pop R0");
        emitStoreVar(*symbol);
        break;
    }
    case ASTNodeType::MEMBER_EXPR: {
        const FieldLayout* field = nullptr;
        emitMemberAddress(static_cast<MemberExpr&>(*node.target), &field);
        if (field != nullptr && structLayoutOf(field->type) != nullptr) {
            // struct 成员整体赋值：逐字拷贝
            emitPopCopyPush(field->sizeWords);
            return;
        }
        if (field != nullptr && isArrayTypeName(field->type)) {
            throw std::runtime_error("Cannot assign to array member: " + field->name);
        }
        emit("    mov R6, R0");
        emit("    pop R0");
        emit("    store [R6], R0");
        break;
    }
    case ASTNodeType::INDEX_EXPR:
    case ASTNodeType::UNARY_EXPR: {
        // a[i] = v / *p = v：目标地址 → R0，弹出值存入；
        // struct 元素/解引用整体赋值 → 逐字拷贝
        emitAddressOf(*node.target);
        const std::string targetType = exprType(*node.target);
        if (const StructLayout* layout = structLayoutOf(targetType)) {
            emitPopCopyPush(std::max(layout->sizeWords, 1));
            return;
        }
        emit("    mov R6, R0");
        emit("    pop R0");
        emit("    store [R6], R0");
        break;
    }
    default:
        throw std::runtime_error("Invalid assignment target");
    }

    // 赋值表达式的值
    emit("    push R0");
}

void CodeGenerator::visit(CallExpr& node) {
    const bool external = m_functions.find(node.callee) == m_functions.end();
    if (external && m_externSet.insert(node.callee).second) {
        m_externs.push_back(node.callee);
    }

    auto returnIt = m_functionReturns.find(node.callee);
    const std::string returnType =
      returnIt != m_functionReturns.end() ? returnIt->second : "int";
    const StructLayout* returnLayout = structLayoutOf(returnType);

    // 参数从右向左求值：a1 最后求值留在栈顶，a5..aN 依序压在栈上；
    // struct 值实参逐字拷贝到调用者临时槽，副本地址作为实参（按值语义）
    for (int i = static_cast<int>(node.arguments.size()) - 1; i >= 0; --i) {
        Expr& argument = *node.arguments[i];
        argument.accept(*this);
        if (structLayoutOf(exprType(argument)) != nullptr) {
            emitStructArgCopy(exprType(argument));
        }
    }

    // 前 4 个参数弹入 R0-R3（fastcall）
    emit("    pop R0");
    if (node.arguments.size() > 1) {
        emit("    pop R1");
    }
    if (node.arguments.size() > 2) {
        emit("    pop R2");
    }
    if (node.arguments.size() > 3) {
        emit("    pop R3");
    }

    // struct 返回（sret）：接收槽地址经 R7 传入
    int sretSlot = 0;
    if (returnLayout != nullptr) {
        sretSlot = allocStructTemp(std::max(returnLayout->sizeWords, 1));
        emit("    mov R7, R5");
        emit("    subi R7, " + std::to_string(4 * sretSlot));
    }

    if (external) {
        emit("    callx " + node.callee);
    } else {
        emit("    call " + node.callee);
    }

    // 第 5 个参数起由调用者清栈
    if (node.arguments.size() > 4) {
        emit("    addi R4, " + std::to_string(4 * (node.arguments.size() - 4)));
    }

    // 返回值压栈：struct → 接收槽地址；标量/指针 → R0
    if (returnLayout != nullptr) {
        emit("    mov R0, R5");
        emit("    subi R0, " + std::to_string(4 * sretSlot));
    }
    emit("    push R0");
}

void CodeGenerator::visit(IdentifierExpr& node) {
    const Symbol* symbol = findSymbol(node.name);
    if (!symbol) {
        throw std::runtime_error("Undefined variable: " + node.name);
    }
    if (isArrayTypeName(symbol->type)) {
        // 数组名退化为首元素地址（传参/赋给指针/比较/条件）
        emitAddressOfSymbol(*symbol);
    } else if (structLayoutOf(symbol->type) != nullptr) {
        // struct 值：地址即值（形参槽位存地址 → load；局部/全局 → 槽地址）
        emitStructAddressOfSymbol(*symbol);
    } else {
        emitLoadVar(*symbol);
    }
    emit("    push R0");
}

void CodeGenerator::visit(IntegerLiteral& node) {
    emit("    lmm R0, " + std::to_string(node.value));
    emit("    push R0");
}

void CodeGenerator::visit(CharLiteral& node) {
    emit("    lmm R0, " + std::to_string(static_cast<int>(node.value)));
    emit("    push R0");
}

void CodeGenerator::visit(StringLiteral& node) {
    // 字符串字面量：数据段标号地址即 char* 值
    const std::string label = internString(node.value);
    emit("    lea R0, " + label);
    emit("    push R0");
}

void CodeGenerator::visit(NullLiteral& node) {
    (void)node;
    emit("    lmm R0, 0");
    emit("    push R0");
}

void CodeGenerator::visit(IndexExpr& node) {
    // a[i] / p[i]：元素地址 → LOAD；struct 元素地址即 struct 值，不 LOAD
    emitElementAddress(node);
    const std::string baseType = decayedTypeName(exprType(*node.base));
    const std::string element =
      isArrayTypeName(baseType) ? arrayElement(baseType) : pointerPointee(baseType);
    if (structLayoutOf(element) == nullptr) {
        emit("    load R0, [R0]");
    }
    emit("    push R0");
}

void CodeGenerator::visit(MemberExpr& node) {
    const FieldLayout* field = nullptr;
    emitMemberAddress(node, &field);
    // 成员为标量/指针 → LOAD 取值；struct/array 成员地址即值（数组名退化）
    const bool loadNeeded =
      field == nullptr
      || (structLayoutOf(field->type) == nullptr && !isArrayTypeName(field->type));
    if (loadNeeded) {
        emit("    load R0, [R0]");
    }
    emit("    push R0");
}

void CodeGenerator::visit(InitListExpr& node) {
    // 初始化器列表只允许作为 struct 声明的初始化器（声明处展开），
    // 出现在一般表达式位置属于内部错误
    (void)node;
    throw std::runtime_error("initializer list is not a first-class expression");
}

void CodeGenerator::visit(StmtVarDeclaration& node) {
    Symbol symbol;
    symbol.kind = SymKind::Local;
    symbol.slot = ++m_nextSlot;
    symbol.type = canonicalType(resolveBaseType(node.type, node.isStructTag),
                                node.pointerDepth,
                                node.isArray);
    symbol.isArray = node.isArray;
    symbol.arraySize = node.arraySize;
    m_localSymbols[node.name] = symbol;

    // 槽位占用：struct 按布局字数；数组按元素数 × 元素字数
    int words = typeSizeWords(symbol.type);
    if (node.isArray) {
        words = std::max(node.arraySize, 1) * typeSizeWords(arrayElement(symbol.type));
    }
    m_nextSlot += std::max(words, 1) - 1;

    if (node.initializer) {
        if (node.initializer->type == ASTNodeType::INIT_LIST_EXPR) {
            // struct 逐成员初始化：成员表达式求值后存入 基址+成员偏移
            auto& initList = static_cast<InitListExpr&>(*node.initializer);
            const StructLayout* layout = structLayoutOf(symbol.type);
            if (layout == nullptr) {
                throw std::runtime_error("array initializers are not supported");
            }
            for (size_t i = 0; i < initList.values.size() && i < layout->fields.size();
                 ++i) {
                initList.values[i]->accept(*this);
                emitStructAddressOfSymbol(symbol); // 基址 → R0
                const FieldLayout& field = layout->fields[i];
                if (field.offsetWords > 0) {
                    emit("    addi R0, " + std::to_string(4 * field.offsetWords));
                }
                emit("    mov R6, R0");
                emit("    pop R0");
                emit("    store [R6], R0");
            }
        } else if (structLayoutOf(symbol.type) != nullptr) {
            // struct 整体初始化：源地址压栈 → 拷贝到变量槽
            node.initializer->accept(*this);
            emitStructAddressOfSymbol(symbol); // 目的地址 → R0
            emitPopCopyPush(typeSizeWords(symbol.type));
            emit("    pop R0"); // 丢弃赋值表达式的结果
        } else {
            node.initializer->accept(*this);
            emit("    pop R0");
            emitStoreVar(symbol);
        }
    }
}

// ---- 地址计算 ----

// 变量地址 → R0（数组名即首元素地址）
// 栈数组占据 slot..slot+size-1 号槽（地址 BP-4·slot 为块内最高地址），
// 首元素固定放在最低地址槽：base = BP - 4*(slot+size-1)，元素向高地址延伸，
// 与指针运算 a[k] == *(a+k) 的语义保持一致
void CodeGenerator::emitAddressOfSymbol(const Symbol& sym) {
    switch (sym.kind) {
    case SymKind::Local: {
        const int elementWords = sym.isArray ? typeSizeWords(arrayElement(sym.type)) : 1;
        const int blockWords =
          sym.isArray ? std::max(sym.arraySize, 1) * elementWords
                      : typeSizeWords(sym.type); // struct 值占多槽；标量/指针 1 槽
        const int slotOffset = sym.slot + std::max(blockWords, 1) - 1;
        emit("    mov R0, R5");
        emit("    subi R0, " + std::to_string(4 * slotOffset));
        break;
    }
    case SymKind::StackArg:
        emit("    mov R0, R5");
        emit("    addi R0, " + std::to_string(4 * (sym.argIndex - 3)));
        break;
    case SymKind::Global:
        emit("    lea R0, " + sym.label);
        break;
    }
}

// 左值表达式地址 → R0：x / a[i] / *p / p.x
void CodeGenerator::emitAddressOf(Expr& expr) {
    switch (expr.type) {
    case ASTNodeType::IDENTIFIER_EXPR: {
        auto& ident = static_cast<IdentifierExpr&>(expr);
        const Symbol* symbol = findSymbol(ident.name);
        if (!symbol) {
            throw std::runtime_error("Undefined variable: " + ident.name);
        }
        if (symbol->isStructParam) {
            // struct 形参：槽位存副本地址（load 即对象地址）
            emitLoadVar(*symbol);
        } else {
            emitAddressOfSymbol(*symbol);
        }
        break;
    }
    case ASTNodeType::INDEX_EXPR:
        emitElementAddress(static_cast<IndexExpr&>(expr));
        break;
    case ASTNodeType::MEMBER_EXPR:
        emitMemberAddress(static_cast<MemberExpr&>(expr), nullptr);
        break;
    case ASTNodeType::UNARY_EXPR:
        if (static_cast<UnaryExpr&>(expr).op == "*") {
            // *p：操作数求值即地址（数组名退化同样成立，*a == a[0]）
            static_cast<UnaryExpr&>(expr).operand->accept(*this);
            emit("    pop R0");
            break;
        }
        throw std::runtime_error("cannot take address of this expression");
    default:
        throw std::runtime_error("cannot take address of this expression");
    }
}

// struct 对象地址 → R0：标识符（局部/全局/形参）、成员、下标、解引用、
// struct 返回调用的临时槽
void CodeGenerator::emitStructValueAddress(Expr& expr) {
    switch (expr.type) {
    case ASTNodeType::IDENTIFIER_EXPR: {
        auto& ident = static_cast<IdentifierExpr&>(expr);
        const Symbol* symbol = findSymbol(ident.name);
        if (!symbol) {
            throw std::runtime_error("Undefined variable: " + ident.name);
        }
        emitStructAddressOfSymbol(*symbol);
        break;
    }
    case ASTNodeType::MEMBER_EXPR:
        emitMemberAddress(static_cast<MemberExpr&>(expr), nullptr);
        break;
    case ASTNodeType::INDEX_EXPR:
        emitElementAddress(static_cast<IndexExpr&>(expr));
        break;
    case ASTNodeType::UNARY_EXPR:
        if (static_cast<UnaryExpr&>(expr).op == "*") {
            static_cast<UnaryExpr&>(expr).operand->accept(*this);
            emit("    pop R0");
            break;
        }
        throw std::runtime_error("cannot obtain address of struct value");
    case ASTNodeType::CALL_EXPR:
        expr.accept(*this); // struct 返回：求值结果 = 接收槽地址
        emit("    pop R0");
        break;
    default:
        throw std::runtime_error("cannot obtain address of struct value");
    }
}

// 成员地址 → R0：基址（dot：struct 值地址；arrow/struct 形参：指针值）+ 偏移
void CodeGenerator::emitMemberAddress(MemberExpr& node, const FieldLayout** outField) {
    const std::string baseType = exprType(*node.base);
    const bool throughPointer = isPointerTypeName(baseType);
    const std::string valueType = throughPointer ? pointerPointee(baseType) : baseType;
    const StructLayout* layout = structLayoutOf(valueType);
    if (layout == nullptr) {
        throw std::runtime_error("member access on non-struct type: " + baseType);
    }
    const FieldLayout* field = findField(*layout, node.member);
    if (field == nullptr) {
        throw std::runtime_error("no member named '" + node.member + "' in " + valueType);
    }
    if (outField != nullptr) {
        *outField = field;
    }

    if (throughPointer) {
        node.base->accept(*this);
        emit("    pop R0"); // 指针值即 struct 地址
    } else {
        emitStructValueAddress(*node.base);
    }
    if (field->offsetWords > 0) {
        emit("    addi R0, " + std::to_string(4 * field->offsetWords));
    }
}

// a[i] / p[i] 元素地址 → R0
// 先求下标压栈暂存，再取基址（下标求值会使用 R0 作暂存，不能先算基址）；
// 元素地址 = 基址 + 元素字数×4×i（数组首元素与指针运算同一语义：a[k] == *(a+k)）
void CodeGenerator::emitElementAddress(IndexExpr& node) {
    // 下标 → 栈
    node.index->accept(*this);

    // 基址 → R0：数组名取首元素地址；其余表达式求值得指针
    if (node.base->type == ASTNodeType::IDENTIFIER_EXPR) {
        auto& ident = static_cast<IdentifierExpr&>(*node.base);
        const Symbol* symbol = findSymbol(ident.name);
        if (symbol && isArrayTypeName(symbol->type)) {
            emitAddressOfSymbol(*symbol);
        } else {
            node.base->accept(*this);
            emit("    pop R0");
        }
    } else {
        node.base->accept(*this);
        emit("    pop R0");
    }

    // 变址：R1 = index × 元素字节数（标量/指针元素 4 字节，struct 元素按布局）
    const std::string baseType = decayedTypeName(exprType(*node.base));
    const std::string element =
      isArrayTypeName(baseType) ? arrayElement(baseType) : pointerPointee(baseType);
    emit("    pop R1");
    emit("    lmm R2, " + std::to_string(4 * typeSizeWords(element)));
    emit("    mul R1, R2");
    emit("    add R0, R1");
}

// 字符串字面量去重入数据段
std::string CodeGenerator::internString(const std::string& content) {
    auto it = m_stringLiterals.find(content);
    if (it != m_stringLiterals.end()) {
        return it->second;
    }
    const std::string label = ".str" + std::to_string(m_stringLiterals.size());
    m_stringLiterals[content] = label;
    return label;
}

// ---- 表达式静态类型推断 ----

std::string CodeGenerator::exprType(const Expr& expr) const {
    switch (expr.type) {
    case ASTNodeType::INTEGER_LITERAL:
    case ASTNodeType::CHAR_LITERAL:
        return "int";
    case ASTNodeType::STRING_LITERAL:
        return "char*";
    case ASTNodeType::NULL_LITERAL:
        return "null";
    case ASTNodeType::IDENTIFIER_EXPR: {
        const Symbol* symbol = findSymbol(static_cast<const IdentifierExpr&>(expr).name);
        return symbol ? symbol->type : "<error>";
    }
    case ASTNodeType::UNARY_EXPR: {
        const auto& unary = static_cast<const UnaryExpr&>(expr);
        if (unary.op == "&") {
            return exprType(*unary.operand) + "*"; // T → T*（struct/标量均适用）
        }
        if (unary.op == "*") {
            const std::string t = decayedTypeName(exprType(*unary.operand));
            if (isPointerTypeName(t)) {
                return pointerPointee(t);
            }
            return "<error>";
        }
        return "int"; // - !
    }
    case ASTNodeType::INDEX_EXPR: {
        const std::string t =
          decayedTypeName(exprType(*static_cast<const IndexExpr&>(expr).base));
        if (isPointerTypeName(t)) {
            return pointerPointee(t);
        }
        return "<error>";
    }
    case ASTNodeType::MEMBER_EXPR: {
        const auto& member = static_cast<const MemberExpr&>(expr);
        const std::string baseType = exprType(*member.base);
        const std::string valueType =
          isPointerTypeName(baseType) ? pointerPointee(baseType) : baseType;
        if (const StructLayout* layout = structLayoutOf(valueType)) {
            if (const FieldLayout* field = findField(*layout, member.member)) {
                return field->type;
            }
        }
        return "<error>";
    }
    case ASTNodeType::BINARY_EXPR: {
        const auto& binary = static_cast<const BinaryExpr&>(expr);
        if (binary.op != "+" && binary.op != "-") {
            return "int"; // 比较/逻辑/乘除模结果均为 int
        }
        const std::string lt = decayedTypeName(exprType(*binary.left));
        const std::string rt = decayedTypeName(exprType(*binary.right));
        if (isPointerTypeName(lt)) {
            return lt; // ptr ± int
        }
        if (isPointerTypeName(rt) && binary.op == "+") {
            return rt; // int + ptr
        }
        return "int";
    }
    case ASTNodeType::ASSIGN_EXPR:
        return exprType(*static_cast<const AssignExpr&>(expr).target);
    case ASTNodeType::CALL_EXPR: {
        auto it = m_functionReturns.find(static_cast<const CallExpr&>(expr).callee);
        return it != m_functionReturns.end() ? it->second : "int";
    }
    default:
        return "<error>";
    }
}
