#include "ncc/codegen.hpp"
#include <algorithm>
#include <stdexcept>

CodeGenerator::CodeGenerator() { m_sink = &m_code; }

std::string CodeGenerator::generate(Program& program) {
    m_code.clear();
    m_data.clear();
    m_labelCounter = 0;
    m_functions.clear();
    m_globalSymbols.clear();
    m_localSymbols.clear();
    m_globalOrder.clear();
    m_globalInits.clear();
    m_registeredGlobals.clear();
    m_externs.clear();
    m_externSet.clear();
    m_breakLabels.clear();
    m_continueLabels.clear();
    m_nextSlot = 0;
    m_sink = &m_code;

    program.accept(*this);

    // 拼装：头注释 + extern 指令 + 函数体 + 数据段
    std::string output;
    output += "; NanoC Generated Assembly (NCI v2.1)\n";
    output += "; Generated by ncc compiler\n\n";
    for (const auto& name : m_externs) {
        output += "extern " + name + "\n";
    }
    if (!m_externs.empty()) {
        output += "\n";
    }
    output += m_code;
    output += m_data;
    return output;
}

void CodeGenerator::emit(const std::string& code) { *m_sink += code + "\n"; }

void CodeGenerator::emitLabel(const std::string& label) { *m_sink += label + ":\n"; }

std::string CodeGenerator::newLabel() { return "L" + std::to_string(m_labelCounter++); }

const CodeGenerator::Symbol* CodeGenerator::findSymbol(const std::string& name) const {
    auto local = m_localSymbols.find(name);
    if (local != m_localSymbols.end()) {
        return &local->second;
    }
    auto global = m_globalSymbols.find(name);
    if (global != m_globalSymbols.end()) {
        return &global->second;
    }
    return nullptr;
}

void CodeGenerator::registerGlobal(VarDeclaration& node) {
    if (!m_registeredGlobals.insert(&node).second) {
        return; // 同一声明只登记一次
    }
    if (m_globalSymbols.find(node.name) == m_globalSymbols.end()) {
        m_globalOrder.push_back(".g_" + node.name);
    }
    Symbol symbol;
    symbol.kind = SymKind::Global;
    symbol.label = ".g_" + node.name;
    symbol.type = node.type;
    m_globalSymbols[node.name] = symbol;

    if (node.initializer) {
        GlobalInit init;
        init.label = symbol.label;
        init.expr = node.initializer.get();
        m_globalInits.push_back(init);
    }
}

void CodeGenerator::emitGlobalInits() {
    for (const auto& init : m_globalInits) {
        init.expr->accept(*this); // 求值结果压栈
        emit("    pop R0");
        emit("    lea R6, " + init.label);
        emit("    store [R6], R0");
    }
}

void CodeGenerator::emitLoadVar(const Symbol& sym) {
    switch (sym.kind) {
    case SymKind::Local:
        emit("    mov R6, R5");
        emit("    subi R6, " + std::to_string(4 * sym.slot));
        emit("    load R0, [R6]");
        break;
    case SymKind::StackArg:
        emit("    mov R6, R5");
        emit("    addi R6, " + std::to_string(4 * (sym.argIndex - 3)));
        emit("    load R0, [R6]");
        break;
    case SymKind::Global:
        emit("    lea R6, " + sym.label);
        emit("    load R0, [R6]");
        break;
    }
}

void CodeGenerator::emitStoreVar(const Symbol& sym) {
    switch (sym.kind) {
    case SymKind::Local:
        emit("    mov R6, R5");
        emit("    subi R6, " + std::to_string(4 * sym.slot));
        break;
    case SymKind::StackArg:
        emit("    mov R6, R5");
        emit("    addi R6, " + std::to_string(4 * (sym.argIndex - 3)));
        break;
    case SymKind::Global:
        emit("    lea R6, " + sym.label);
        break;
    }
    emit("    store [R6], R0");
}

void CodeGenerator::emitTestBranch(const std::string& target, bool branchOnTrue) {
    // TEST R, R：按位 AND 置 flags（0 → Z，负 → N，正 → P）
    emit("    test R0, R0");
    emit(std::string("    ") + (branchOnTrue ? "jnz " : "jz ") + target);
}

void CodeGenerator::emitCompareBranch(const std::string& op,
                                      const std::string& target,
                                      bool branchOnTrue) {
    // flags 由 CMP 置位：Z = 相等、N = 左 < 右、P = 左 > 右
    // 无 JNN/JNP，Z|N / Z|P 类条件用两次跳转复合
    emit("    cmp R0, R1");
    auto jump = [&](const std::string& mnemonic) {
        emit("    " + mnemonic + " " + target);
    };
    if (op == "==") {
        branchOnTrue ? jump("jz") : jump("jnz");
    } else if (op == "!=") {
        branchOnTrue ? jump("jnz") : jump("jz");
    } else if (op == "<") {
        branchOnTrue ? jump("jn") : (jump("jz"), jump("jp"));
    } else if (op == "<=") {
        branchOnTrue ? (jump("jz"), jump("jn")) : jump("jp");
    } else if (op == ">") {
        branchOnTrue ? jump("jp") : (jump("jz"), jump("jn"));
    } else if (op == ">=") {
        branchOnTrue ? (jump("jz"), jump("jp")) : jump("jn");
    } else {
        throw std::runtime_error("Unknown comparison operator: " + op);
    }
}

void CodeGenerator::emitCompareValue(const std::string& op) {
    // 比较作为表达式值时物化为 0/1：条件成立 → 1，否则 → 0
    const std::string trueLabel = newLabel();
    const std::string endLabel = newLabel();
    emit("    cmp R0, R1");
    if (op == "==") {
        emit("    jz " + trueLabel);
    } else if (op == "!=") {
        emit("    jnz " + trueLabel);
    } else if (op == "<") {
        emit("    jn " + trueLabel);
    } else if (op == "<=") {
        emit("    jz " + trueLabel);
        emit("    jn " + trueLabel);
    } else if (op == ">") {
        emit("    jp " + trueLabel);
    } else if (op == ">=") {
        emit("    jz " + trueLabel);
        emit("    jp " + trueLabel);
    } else {
        throw std::runtime_error("Unknown comparison operator: " + op);
    }
    emit("    lmm R2, 0");
    emit("    jmp " + endLabel);
    emitLabel(trueLabel);
    emit("    lmm R2, 1");
    emitLabel(endLabel);
    emit("    push R2");
}

void CodeGenerator::emitBranchFalse(Expr& expr, const std::string& target) {
    emitBranch(expr, target, false);
}

void CodeGenerator::emitBranchTrue(Expr& expr, const std::string& target) {
    emitBranch(expr, target, true);
}

void CodeGenerator::emitBranch(Expr& expr, const std::string& target, bool branchOnTrue) {
    if (expr.type == ASTNodeType::BINARY_EXPR) {
        auto& binary = static_cast<BinaryExpr&>(expr);
        if (binary.op == "&&") {
            // 左假即假；左右皆真才为真
            if (branchOnTrue) {
                const std::string falseLabel = newLabel();
                emitBranchFalse(*binary.left, falseLabel);
                emitBranchTrue(*binary.right, target);
                emitLabel(falseLabel);
            } else {
                emitBranchFalse(*binary.left, target);
                emitBranchFalse(*binary.right, target);
            }
            return;
        }
        if (binary.op == "||") {
            // 左真即真；左右皆假才为假
            if (branchOnTrue) {
                emitBranchTrue(*binary.left, target);
                emitBranchTrue(*binary.right, target);
            } else {
                const std::string trueLabel = newLabel();
                emitBranchTrue(*binary.left, trueLabel);
                emitBranchFalse(*binary.right, target);
                emitLabel(trueLabel);
            }
            return;
        }
        if (binary.op == "==" || binary.op == "!=" || binary.op == "<"
            || binary.op == "<=" || binary.op == ">" || binary.op == ">=") {
            binary.left->accept(*this);
            binary.right->accept(*this);
            emit("    pop R1");
            emit("    pop R0");
            emitCompareBranch(binary.op, target, branchOnTrue);
            return;
        }
    }
    if (expr.type == ASTNodeType::UNARY_EXPR) {
        auto& unary = static_cast<UnaryExpr&>(expr);
        if (unary.op == "!") {
            emitBranch(*unary.operand, target, !branchOnTrue);
            return;
        }
    }
    // 其余表达式：求值后按真值跳转
    expr.accept(*this);
    emit("    pop R0");
    emitTestBranch(target, branchOnTrue);
}

int CodeGenerator::countLocalSlots(Stmt* stmt) const {
    if (!stmt) {
        return 0;
    }
    switch (stmt->type) {
    case ASTNodeType::COMPOUND_STMT: {
        auto& compound = static_cast<CompoundStmt&>(*stmt);
        int count = 0;
        for (auto& child : compound.statements) {
            count += countLocalSlots(child.get());
        }
        return count;
    }
    case ASTNodeType::VAR_DECLARATION: // 语句上下文的声明节点（StmtVarDeclaration）
        return 1;
    case ASTNodeType::IF_STMT: {
        auto& ifStmt = static_cast<IfStmt&>(*stmt);
        return countLocalSlots(ifStmt.thenBranch.get())
               + countLocalSlots(ifStmt.elseBranch.get());
    }
    case ASTNodeType::WHILE_STMT:
        return countLocalSlots(static_cast<WhileStmt&>(*stmt).body.get());
    case ASTNodeType::FOR_STMT: {
        auto& forStmt = static_cast<ForStmt&>(*stmt);
        return countLocalSlots(forStmt.init.get()) + countLocalSlots(forStmt.body.get());
    }
    default:
        return 0;
    }
}

void CodeGenerator::visit(Program& node) {
    // 第一遍：登记函数符号（允许前向引用）与全局变量
    for (auto& decl : node.declarations) {
        if (decl->type == ASTNodeType::FUNC_DECLARATION) {
            auto& func = static_cast<FuncDeclaration&>(*decl);
            m_functions.insert(func.name);
        } else if (decl->type == ASTNodeType::VAR_DECLARATION) {
            registerGlobal(static_cast<VarDeclaration&>(*decl));
        }
    }

    // 第二遍：逐函数生成
    bool hasMain = false;
    for (auto& decl : node.declarations) {
        if (decl->type != ASTNodeType::FUNC_DECLARATION) {
            continue;
        }
        auto& func = static_cast<FuncDeclaration&>(*decl);
        if (func.name == "main") {
            hasMain = true;
        }
        decl->accept(*this);
    }

    // 缺省 main：空函数，由 VM 栈底哨兵终止
    if (!hasMain) {
        emit("");
        emit("; Default main function");
        emitLabel("main");
        emit("    enter 0");
        emitGlobalInits();
        emit("    leave");
        emit("    ret");
    }

    // 数据段：全局变量标号地址 = codeSize + 段内偏移（nas 统一编址回填）
    if (!m_globalOrder.empty()) {
        m_sink = &m_data;
        emit("");
        emit("; Data segment");
        for (const auto& label : m_globalOrder) {
            emitLabel(label);
            emit("    dd 0");
        }
        m_sink = &m_code;
    }
}

void CodeGenerator::visit(VarDeclaration& node) {
    // 全局变量：只登记数据标号（已由 visit(Program) 预登记，此处兜底）
    registerGlobal(node);
}

void CodeGenerator::visit(FuncDeclaration& node) {
    m_functions.insert(node.name);
    m_localSymbols.clear();
    m_nextSlot = 0;
    const bool isMain = (node.name == "main");

    emit("");
    emit("; Function: " + node.name);
    emitLabel(node.name);

    // fastcall：前 4 个参数占帧槽位（入口溢出保存），第 5 个起在调用者栈上
    const int regParams = static_cast<int>(std::min<size_t>(node.parameters.size(), 4));
    for (int i = 0; i < regParams; ++i) {
        Symbol symbol;
        symbol.kind = SymKind::Local;
        symbol.slot = i + 1;
        symbol.type = node.parameters[i]->type;
        m_localSymbols[node.parameters[i]->name] = symbol;
    }
    for (size_t i = 4; i < node.parameters.size(); ++i) {
        Symbol symbol;
        symbol.kind = SymKind::StackArg;
        symbol.argIndex = static_cast<int>(i) + 1;
        symbol.type = node.parameters[i]->type;
        m_localSymbols[node.parameters[i]->name] = symbol;
    }
    m_nextSlot = regParams;

    const int enterSize = 4 * (m_nextSlot + countLocalSlots(node.body.get()));
    emit("    enter " + std::to_string(enterSize));

    // 溢出寄存器参数到帧槽位
    for (int i = 0; i < regParams; ++i) {
        emit("    mov R6, R5");
        emit("    subi R6, " + std::to_string(4 * (i + 1)));
        emit("    store [R6], R" + std::to_string(i));
    }

    // main：先执行全局变量初始化（此时寄存器参数已溢出，可自由使用 R0/R6）
    if (isMain) {
        emitGlobalInits();
    }

    if (node.body) {
        node.body->accept(*this);
    }

    emit("    leave");
    emit("    ret");
    m_localSymbols.clear();
}

void CodeGenerator::visit(CompoundStmt& node) {
    for (auto& stmt : node.statements) {
        stmt->accept(*this);
    }
}

void CodeGenerator::visit(IfStmt& node) {
    const std::string endLabel = newLabel();
    if (node.elseBranch) {
        const std::string elseLabel = newLabel();
        emitBranchFalse(*node.condition, elseLabel);
        if (node.thenBranch) {
            node.thenBranch->accept(*this);
        }
        emit("    jmp " + endLabel);
        emitLabel(elseLabel);
        node.elseBranch->accept(*this);
    } else {
        emitBranchFalse(*node.condition, endLabel);
        if (node.thenBranch) {
            node.thenBranch->accept(*this);
        }
    }
    emitLabel(endLabel);
}

void CodeGenerator::visit(WhileStmt& node) {
    const std::string loopLabel = newLabel();
    const std::string endLabel = newLabel();

    m_breakLabels.push_back(endLabel);
    m_continueLabels.push_back(loopLabel);

    emitLabel(loopLabel);
    emitBranchFalse(*node.condition, endLabel);
    if (node.body) {
        node.body->accept(*this);
    }
    emit("    jmp " + loopLabel);
    emitLabel(endLabel);

    m_breakLabels.pop_back();
    m_continueLabels.pop_back();
}

void CodeGenerator::visit(ForStmt& node) {
    const std::string loopLabel = newLabel();
    const std::string continueLabel = newLabel();
    const std::string endLabel = newLabel();

    m_breakLabels.push_back(endLabel);
    m_continueLabels.push_back(continueLabel);

    if (node.init) {
        node.init->accept(*this);
    }
    emitLabel(loopLabel);
    if (node.condition) {
        emitBranchFalse(*node.condition, endLabel);
    }
    if (node.body) {
        node.body->accept(*this);
    }
    emitLabel(continueLabel);
    if (node.increment) {
        node.increment->accept(*this);
    }
    emit("    jmp " + loopLabel);
    emitLabel(endLabel);

    m_breakLabels.pop_back();
    m_continueLabels.pop_back();
}

void CodeGenerator::visit(ReturnStmt& node) {
    if (node.value) {
        node.value->accept(*this);
        emit("    pop R0"); // 返回值统一在 R0
    }
    emit("    leave");
    emit("    ret");
}

void CodeGenerator::visit(BreakStmt& node) {
    if (m_breakLabels.empty()) {
        throw std::runtime_error("break statement not within loop");
    }
    emit("    jmp " + m_breakLabels.back());
}

void CodeGenerator::visit(ContinueStmt& node) {
    if (m_continueLabels.empty()) {
        throw std::runtime_error("continue statement not within loop");
    }
    emit("    jmp " + m_continueLabels.back());
}

void CodeGenerator::visit(ExprStmt& node) {
    if (node.expression) {
        node.expression->accept(*this);
        emit("    pop R0"); // 表达式语句的结果被丢弃
    }
}

void CodeGenerator::visit(BinaryExpr& node) {
    if (node.op == "&&") {
        const std::string falseLabel = newLabel();
        const std::string endLabel = newLabel();
        emitBranchFalse(node, falseLabel);
        emit("    lmm R0, 1");
        emit("    push R0");
        emit("    jmp " + endLabel);
        emitLabel(falseLabel);
        emit("    lmm R0, 0");
        emit("    push R0");
        emitLabel(endLabel);
        return;
    }
    if (node.op == "||") {
        const std::string trueLabel = newLabel();
        const std::string endLabel = newLabel();
        emitBranchTrue(node, trueLabel);
        emit("    lmm R0, 0");
        emit("    push R0");
        emit("    jmp " + endLabel);
        emitLabel(trueLabel);
        emit("    lmm R0, 1");
        emit("    push R0");
        emitLabel(endLabel);
        return;
    }
    if (node.op == "==" || node.op == "!=" || node.op == "<" || node.op == "<="
        || node.op == ">" || node.op == ">=") {
        node.left->accept(*this);
        node.right->accept(*this);
        emit("    pop R1"); // 右操作数
        emit("    pop R0"); // 左操作数
        emitCompareValue(node.op);
        return;
    }

    // 算术运算：左操作数先压栈，右操作数在栈顶
    node.left->accept(*this);
    node.right->accept(*this);
    emit("    pop R1"); // 右操作数
    emit("    pop R0"); // 左操作数

    if (node.op == "+") {
        emit("    add R0, R1");
    } else if (node.op == "-") {
        emit("    sub R0, R1");
    } else if (node.op == "*") {
        emit("    mul R0, R1");
    } else if (node.op == "/") {
        emit("    div R0, R1");
    } else if (node.op == "%") {
        emit("    mod R0, R1");
    } else {
        throw std::runtime_error("Unknown binary operator: " + node.op);
    }
    emit("    push R0");
}

void CodeGenerator::visit(UnaryExpr& node) {
    node.operand->accept(*this);
    emit("    pop R0");

    if (node.op == "-") {
        emit("    neg R0");
        emit("    push R0");
    } else if (node.op == "!") {
        // 逻辑非：test 置 flags 后物化 0/1
        const std::string nonzeroLabel = newLabel();
        const std::string endLabel = newLabel();
        emit("    test R0, R0");
        emit("    jnz " + nonzeroLabel);
        emit("    lmm R2, 1");
        emit("    jmp " + endLabel);
        emitLabel(nonzeroLabel);
        emit("    lmm R2, 0");
        emitLabel(endLabel);
        emit("    push R2");
    } else {
        throw std::runtime_error("Unknown unary operator: " + node.op);
    }
}

void CodeGenerator::visit(AssignExpr& node) {
    node.value->accept(*this);
    emit("    pop R0");

    const Symbol* symbol = findSymbol(node.name);
    if (!symbol) {
        throw std::runtime_error("Undefined variable: " + node.name);
    }
    emitStoreVar(*symbol);

    // 赋值表达式的值
    emit("    push R0");
}

void CodeGenerator::visit(CallExpr& node) {
    const bool external = m_functions.find(node.callee) == m_functions.end();
    if (external && m_externSet.insert(node.callee).second) {
        m_externs.push_back(node.callee);
    }

    // 参数从右向左求值：a1 最后求值留在栈顶，a5..aN 依序压在栈上
    for (int i = static_cast<int>(node.arguments.size()) - 1; i >= 0; --i) {
        node.arguments[i]->accept(*this);
    }

    // 前 4 个参数弹入 R0-R3（fastcall）
    emit("    pop R0");
    if (node.arguments.size() > 1) {
        emit("    pop R1");
    }
    if (node.arguments.size() > 2) {
        emit("    pop R2");
    }
    if (node.arguments.size() > 3) {
        emit("    pop R3");
    }

    if (external) {
        emit("    callx " + node.callee);
    } else {
        emit("    call " + node.callee);
    }

    // 第 5 个参数起由调用者清栈
    if (node.arguments.size() > 4) {
        emit("    addi R4, " + std::to_string(4 * (node.arguments.size() - 4)));
    }

    // 返回值在 R0，压栈
    emit("    push R0");
}

void CodeGenerator::visit(IdentifierExpr& node) {
    const Symbol* symbol = findSymbol(node.name);
    if (!symbol) {
        throw std::runtime_error("Undefined variable: " + node.name);
    }
    emitLoadVar(*symbol);
    emit("    push R0");
}

void CodeGenerator::visit(IntegerLiteral& node) {
    emit("    lmm R0, " + std::to_string(node.value));
    emit("    push R0");
}

void CodeGenerator::visit(CharLiteral& node) {
    emit("    lmm R0, " + std::to_string(static_cast<int>(node.value)));
    emit("    push R0");
}

void CodeGenerator::visit(StmtVarDeclaration& node) {
    Symbol symbol;
    symbol.kind = SymKind::Local;
    symbol.slot = ++m_nextSlot;
    symbol.type = node.type;
    m_localSymbols[node.name] = symbol;

    if (node.initializer) {
        node.initializer->accept(*this);
        emit("    pop R0");
        emitStoreVar(symbol);
    }
}
